config/routes.rb
Rails.application.routes.draw do
  resources :conservations
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'conservations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/conservation.rb
class Conservation < ApplicationRecord
	geocoded_by :address
	reverse_geocoded_by :latitude, :longitude,
  :address => :address
	after_validation :reverse_geocode,  :if => lambda{ |obj| (obj.longitude_changed? || latitude_changed?) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include Pagy::Backend
end

app/controllers/conservations_controller.rb
class ConservationsController < ApplicationController
  before_action :set_conservation, only: %i[ show edit update destroy ]

  # GET /conservations or /conservations.json
  def index
   # @conservations = Conservation.all
    
  if params[:query].present?
    @pagy, @conservations  = pagy(Conservation.where("address LIKE ?", "%#{params[:query]}%")) 
  else
     @pagy, @conservations = pagy(Conservation.all)
  end

  if turbo_frame_request?
    render partial: "conservations", locals: { conservations: @conservations }
  else
    render :index
  end
  
  end

  # GET /conservations/1 or /conservations/1.json
  def show
  end

  # GET /conservations/new
  def new
    @conservation = Conservation.new
  end

  # GET /conservations/1/edit
  def edit
  end

  # POST /conservations or /conservations.json
  def create
    @conservation = Conservation.new(conservation_params)

    respond_to do |format|
      if @conservation.save
        format.html { redirect_to conservation_url(@conservation), notice: "Conservation was successfully created." }
        format.json { render :show, status: :created, location: @conservation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @conservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /conservations/1 or /conservations/1.json
  def update
    respond_to do |format|
      if @conservation.update(conservation_params)
        format.html { redirect_to conservation_url(@conservation), notice: "Conservation was successfully updated." }
        format.json { render :show, status: :ok, location: @conservation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @conservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /conservations/1 or /conservations/1.json
  def destroy
    @conservation.destroy

    respond_to do |format|
      format.html { redirect_to conservations_url, notice: "Conservation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_conservation
      @conservation = Conservation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def conservation_params
      params.require(:conservation).permit(:name, :address, :polygonid, :partid, :pointid, :longitude, :latitude, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	include Pagy::Frontend
end

app/helpers/conservations_helper.rb
module ConservationsHelper
end

app/views/conservations/_conservation.html.erb
<div id="<%= dom_id conservation %>">
  <p>
    <strong>Name:</strong>
    <%= conservation.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= conservation.address %>
  </p>

  <p>
    <strong>Polygonid:</strong>
    <%= conservation.polygonid %>
  </p>

  <p>
    <strong>Partid:</strong>
    <%= conservation.partid %>
  </p>

  <p>
    <strong>Pointid:</strong>
    <%= conservation.pointid %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= conservation.longitude %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= conservation.latitude %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= conservation.description %>
  </p>

</div>

app/views/conservations/_conservations.html.erb
<%= turbo_frame_tag "conservations" do %>
  <div class="container">

  <div class="row">
  	<h1>Conservations</h1>
    <div class="col-6 col-lg-6 background">
      <%== pagy_bootstrap_nav(@pagy) %>
<table id="users" class="table table-striped table-hover table-bordered">
  <thead class="table-dark">
    <tr>
      <th scope="col">Address</th>
      <th scope="col">Name</th>
      <th scope="col">Longitude</th>
      <th scope="col">Latitude</th>
    </tr>
  </thead>
  <tbody>
  	 <% @conservations.each do |conservation| %>
     <tr>
      <td><%= link_to conservation.address, conservation %></td>
      <td><%= conservation.name %></td>
      <td><%= conservation.longitude %></td>
      <td><%= conservation.latitude %></td>
    </tr>
  <% end %>

   
  </tbody>
</table>
<p>
	<%= link_to "New conservation", new_conservation_path , class:"btn btn-dark" %>
</p>
    </div>
    <div class="col-6 col-lg-6 background2">
      <div class="my-6">
  <%= render "conservationsearch", conservations: @conservations %>
    </div>
     
    </div>
  </div>
</div>
<% end %>

app/views/conservations/_conservationsearch.html.erb
<%= form_with(url: conservations_path, method: :get, data: {controller: "search-form",turbo_frame: "conservations", turbo_action: "advance"}) do |form| %>

  

  <div class="my-3 text-left">
  	 <div class="row">
  	 	<div class="col">
  	 		<h4>Conservations</h4>
  	 		<%= form.label :query, "Search by address of conservation:", class: "block mb-2" %>
  	 	</div>
  	 	
  	 </div>
  
  <div class="row">
    <div class="col">
       <%= form.text_field :query, class: "rounded form-control", placHolder: "Search by address of conservation", data: {action: "input->search-form#search"} %>
    </div>
    <div class="col">
      <%= form.submit 'Search', class: "btn btn-dark", id:"conservationsearch" %>
    </div>
  </div>
</div>
<% end %>

app/views/conservations/_form.html.erb
<%= form_with(model: conservation, data: { controller: :maps, action: "google-maps-callback@window->maps#initializeMap"} ) do |form| %>
  <% if conservation.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(conservation.errors.count, "error") %> prohibited this conservation from being saved:</h2>

      <ul>
        <% conservation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="row">
    
    <div class="col-6 col-lg-6 background">
      <div class="form-group my-2">
    <%= form.label :name, style: "display: block" , class:"form-label" %>
    <%= form.text_field :name,  class:"form-control" %>
  </div>

  <div>
    <%= form.label :address, style: "display: block", class:"form-label" %>
    <%= form.text_field :address,  class:"form-control" %>
  </div>

  <div>
    <%= form.label :polygonid, style: "display: block", class:"form-label" %>
    <%= form.number_field :polygonid ,  class:"form-control" %>
  </div>

  <div>
    <%= form.label :partid, style: "display: block", class:"form-label" %>
    <%= form.number_field :partid,  class:"form-control" %>
  </div>

  <div>
    <%= form.label :pointid, style: "display: block", class:"form-label" %>
    <%= form.number_field :pointid,  class:"form-control" %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block", class:"form-label" %>
    <%= form.text_field :longitude, data: { target: "maps.longitude"},  class:"form-control"  %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block", class:"form-label" %>
    <%= form.text_field :latitude, data: { target: "maps.latitude"},  class:"form-control" %>
  </div>

  <div>
    <%= form.label :description, style: "display: block", class:"form-label" %>
    <%= form.text_field :description,  class:"form-control" %>
  </div>

  <div class="mt-4">
    <%= form.submit  class:"btn btn-dark" %>

  </div>
    </div>
    <div class="col-6 col-lg-6 background2">
      <p><%= content_tag :div,nil,data: {target: "maps.map"}, class: "c-map" %></p>
    </div>
  </div>

  
<% end %>

app/views/conservations/edit.html.erb
<div class="container my-2">
<h2>Update Conservation</h2>
<%= render "form", conservation: @conservation %>

<br>

<div>
  <%= link_to "Show this conservation", @conservation , class:"btn btn-dark" %> 
  <%= link_to "Back to conservations", conservations_path , class:"btn btn-dark"%>
</div>
</div>

app/views/conservations/index.html.erb
<div data-controller="listing-map" data-action="google-maps-callback@window->listing-map#initializeMap">
<div class="row">
<div class="col-12"> 
  <%= render "conservationsearch", conservations: @conservations %>
  </div>
</div>
  <div class="row">
  	
    <div class="col-6 col-lg-6 background">
      <%== pagy_bootstrap_nav(@pagy) %>
          <table class="table table-striped table-hover table-bordered" data-listing-map-target="conservations">
            <thead class="table-dark">
              <tr>
                <th scope="col">Address</th>
                <th scope="col">Name</th>
                <th scope="col">Longitude</th>
                <th scope="col">Latitude</th>
              </tr>
            </thead>
            <tbody>
            	 <% @conservations.each do |conservation| %>
               <tr data-longitude=<%=conservation.longitude%> data-latitude=<%=conservation.latitude%>>
                <td><%= link_to conservation.address, conservation %></td>
                <td><%= conservation.name %></td>
                <td><%= conservation.longitude %></td>
                <td><%= conservation.latitude %></td>
              </tr>
            <% end %>
            </tbody>
          </table>
          
          <p>
          	<%= link_to "New conservation", new_conservation_path , class:"btn btn-dark" %>
          </p>
    </div>
    <div class="col-6 col-lg-6">
      <div class="my-6 p-3 c-map-home" data-listing-map-target="map">
 
    </div>
     
    </div>
  </div>
</div>

app/views/conservations/new.html.erb
<div class="container my-2">
<h1>New conservation</h1>

<%= render "form", conservation: @conservation %>

<br>

<div>
  <%= link_to "Back to conservations", conservations_path , class:"btn btn-dark"%>
</div>
</div>

app/views/conservations/show.html.erb
<div class="my-2" data-controller="maps" data-action="google-maps-callback@window->map#initializeMap">
<div class="card" style="30%">
 
</p>
  <div class="card-body">
    <h3 class="card-text"><%= @conservation.name %></h3>
    <h6 class="card-title"><%= @conservation.address %></h6>
     <p class="c-map-view" data-maps-target="map">
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><h6><%= @conservation.description %></h6></li>
    <li class="list-group-item" data-maps-target="longitude"><h6>Longitude:-</h6><%= @conservation.longitude %></li>
    <li class="list-group-item" data-maps-target="latitude"><h6>Latitude:-</h6><%= @conservation.latitude %></li>
  </ul>
  <div class="card-body">
  	 <ul class="list-group list-group-flush list-group-horizontal">
    <li class="list-group-item">
    	<%= link_to "Edit this conservation", edit_conservation_path(@conservation), class:"btn btn-dark" %> 
    	
    </li>
    <li class="list-group-item">
    	<%= link_to "Back to conservations", conservations_path, class:"btn btn-dark" %>
    </li>
    <li class="list-group-item">
    	<%= button_to "Destroy this conservation", @conservation, method: :delete , class:"btn btn-dark" %>
    </li>
  </ul>
  </div>
</div>

</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-dark bg-dark bg-light">
  <div class="container-fluid">
    <a class="navbar-brand " href="/">
      <img src="../logo.webp" alt="" width="auto" height="80" class="d-inline-block align-text-top">
    </a>

  </div>
</nav>

app/views/layouts/_alerts.html.erb
<div class=" alert alert-dark my-3" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Conservationmap</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
 <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %> 
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <%= javascript_importmap_tags %>
   <script 
    src="https://maps.googleapis.com/maps/api/js?key=<%=  Rails.configuration.google_maps_api_key %>&libraries=places&callback=dispatchMapsEvent" async defer data-turbolinks-eval="false" >
    </script>
  </head>

  <body>
    <%= render 'home/header' %>
    <div class="container">
      <% if notice %>
      <%= render 'layouts/alerts' %>
      <% end %>
     
    <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>